name: mat223-notion2github
# on:
#   schedule:
#     - cron: '0 0 * * *'
on: [push]
jobs:
  auto-sync-from-notion-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notion2Github
        uses: younho9/notion2github@v1.1.0
        with:
          database-url: 'https://www.notion.so/dlazaro/9f1197ac443f42768dd17f3f7c03b49b'
          docs-directory: ./mat223
          filter-prop: Course
          filter-value: MAT223
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Format documents
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write ./mat223/**/*.md
          commit_message: 'mat223: Update notes (auto)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
